### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by CriminalAcorns** [Z8pn/RageSurvival#6]
I get in the game after following all steps and it loads everything up but nothing in-game changes. It's just default

I get this in my server.exe window : ""Error: Error: Cannot find module 'rage-rpc'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\RageMP\server-files\packages\RageSurvival\index.js:2:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)""

And my gamemode doesn't change it still says "freemode"
Also "127.0.0.1:55252 has been disconnected."
This happens every few minutes in the server window

**Comment by Z8pn** [comment]
try npm i rage-rpc

**Comment by CriminalAcorns** [comment]
Is the gamemode supposed to still say "freeroam"?

**Comment by Z8pn** [comment]
it says what you set it to, the code doesn't change the displayed gamemode.

**Comment by CriminalAcorns** [comment]
Oh okay. But I'm in-game and it's just normal, still nothing has changed! >.>

**Comment by CriminalAcorns** [comment]
>.>
